name: news_app
description: "news app with flutter and bloc state management"
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  #state management
  flutter_bloc: ^8.1.3
  #comparing dart object
  equatable: ^2.0.5
  #service locator
  get_it: ^7.6.7
  #dateformat
  intl: ^0.19.0
  #Database
  floor: ^1.4.2
  #make request to api
  retrofit: ^4.0.3
  #hooks
  flutter_hooks: ^0.20.4
  #cache image
  cached_network_image: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  retrofit_generator: ^8.0.6
  floor_generator: ^1.4.2
  build_runner: ^2.4.8

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Light.ttf
          weight: 300